restart: Unknown instance: 
/bin/sh: 1: /home/ubuntu/FrameworkBenchmarks/installs/py3/bin/pip: not found
2014-06-29 02:22:32 [1943] [INFO] Starting gunicorn 18.0
2014-06-29 02:22:32 [1943] [INFO] Listening at: http://0.0.0.0:6543 (1943)
2014-06-29 02:22:32 [1943] [INFO] Using worker: sync
2014-06-29 02:22:32 [1946] [INFO] Booting worker with pid: 1946
2014-06-29 02:22:32 [1946] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1946] [INFO] Worker exiting (pid: 1946)
2014-06-29 02:22:32 [1947] [INFO] Booting worker with pid: 1947
2014-06-29 02:22:32 [1947] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1947] [INFO] Worker exiting (pid: 1947)
2014-06-29 02:22:32 [1948] [INFO] Booting worker with pid: 1948
2014-06-29 02:22:32 [1948] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1948] [INFO] Worker exiting (pid: 1948)
2014-06-29 02:22:32 [1949] [INFO] Booting worker with pid: 1949
2014-06-29 02:22:32 [1949] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1949] [INFO] Worker exiting (pid: 1949)
2014-06-29 02:22:32 [1950] [INFO] Booting worker with pid: 1950
2014-06-29 02:22:32 [1950] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1950] [INFO] Worker exiting (pid: 1950)
2014-06-29 02:22:32 [1951] [INFO] Booting worker with pid: 1951
2014-06-29 02:22:32 [1951] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1951] [INFO] Worker exiting (pid: 1951)
2014-06-29 02:22:32 [1952] [INFO] Booting worker with pid: 1952
2014-06-29 02:22:32 [1953] [INFO] Booting worker with pid: 1953
2014-06-29 02:22:32 [1952] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1952] [INFO] Worker exiting (pid: 1952)
2014-06-29 02:22:32 [1953] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1953] [INFO] Worker exiting (pid: 1953)
2014-06-29 02:22:32 [1954] [INFO] Booting worker with pid: 1954
2014-06-29 02:22:32 [1954] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1954] [INFO] Worker exiting (pid: 1954)
2014-06-29 02:22:32 [1955] [INFO] Booting worker with pid: 1955
2014-06-29 02:22:32 [1955] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1955] [INFO] Worker exiting (pid: 1955)
2014-06-29 02:22:32 [1956] [INFO] Booting worker with pid: 1956
2014-06-29 02:22:32 [1956] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1956] [INFO] Worker exiting (pid: 1956)
2014-06-29 02:22:32 [1957] [INFO] Booting worker with pid: 1957
2014-06-29 02:22:32 [1957] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/workers/base.py", line 106, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/base.py", line 114, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.4/site-packages/gunicorn/util.py", line 354, in import_app
    __import__(module)
  File "/home/ubuntu/FrameworkBenchmarks/pyramid/wsgi.py", line 1, in <module>
    from paste.deploy import loadapp
ImportError: No module named 'paste'
2014-06-29 02:22:32 [1957] [INFO] Worker exiting (pid: 1957)

Error: dictionary changed size during iteration

curl: (7) Failed to connect to 127.0.0.1 port 6543: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 6543: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 6543: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 6543: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 6543: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 6543: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 6543: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 6543: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 6543: Connection refused
